# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: {{ include "graphrag.fullname" . }}
  labels:
    {{- include "graphrag.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.port }}
      protocol: TCP
      name: graphrag
  selector:
    {{- include "graphrag.selectorLabels" . | nindent 4 }}
    app: {{ include "graphrag.fullname" . }}
